// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwo2_dPtBPVNInwu5T03qxXgvnWMlNXtY',
    appId: '1:950866380354:web:be620974e92bf0725d8fdb',
    messagingSenderId: '950866380354',
    projectId: 'todo-57f37',
    authDomain: 'todo-57f37.firebaseapp.com',
    storageBucket: 'todo-57f37.appspot.com',
    measurementId: 'G-PQJJJQJ2H6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCYBxY4JWu3dzJdNFRyea4EaFEA9XwRyw',
    appId: '1:950866380354:android:0ca57784fc5185325d8fdb',
    messagingSenderId: '950866380354',
    projectId: 'todo-57f37',
    storageBucket: 'todo-57f37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZirhSfdteZ3JuHxUXlV2nzN3SsNqECBc',
    appId: '1:950866380354:ios:703282a9bc20b4295d8fdb',
    messagingSenderId: '950866380354',
    projectId: 'todo-57f37',
    storageBucket: 'todo-57f37.appspot.com',
    iosBundleId: 'com.example.ToDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZirhSfdteZ3JuHxUXlV2nzN3SsNqECBc',
    appId: '1:950866380354:ios:703282a9bc20b4295d8fdb',
    messagingSenderId: '950866380354',
    projectId: 'todo-57f37',
    storageBucket: 'todo-57f37.appspot.com',
    iosBundleId: 'com.example.ToDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwo2_dPtBPVNInwu5T03qxXgvnWMlNXtY',
    appId: '1:950866380354:web:4044dbccff3b8d775d8fdb',
    messagingSenderId: '950866380354',
    projectId: 'todo-57f37',
    authDomain: 'todo-57f37.firebaseapp.com',
    storageBucket: 'todo-57f37.appspot.com',
    measurementId: 'G-D7D3QNJVMT',
  );
}
